### ISSUE TITLE
Problema al comando "vagrant up"

### ISSUE THREAD

**Issue by frakbe** [daserzw/IdP3-vagrant#1]
`franco@worktop:~/compilati/IdP3-vagrant-master$ vagrant up
Bringing machine 'default' up with 'libvirt' provider...
==> default: Box 'ubuntu/trusty32' could not be found. Attempting to find and install...
    default: Box Provider: libvirt
    default: Box Version: >= 0
==> default: Loading metadata for box 'ubuntu/trusty32'
    default: URL: https://atlas.hashicorp.com/ubuntu/trusty32
The box you're attempting to add doesn't support the provider
you requested. Please find an alternate box or use an alternate
provider. Double-check your requested provider to verify you didn't
simply misspell it.

If you're adding a box from HashiCorp's Atlas, make sure the box is
released.

Name: ubuntu/trusty32
Address: https://atlas.hashicorp.com/ubuntu/trusty32
Requested provider: [:libvirt]
`
Ambiente Fedora 23 x64.
Vagrant, libvirt e vagrant-libvirt provider installati da repo ufficiale di Fedora.
Versione di Vagrant: 1.8.1
Versione di libvirt: 1.2.18.3
Versione di VirtualBox: 5.0.20

**Comment by frakbe** [comment]
Risolto, posto la soluzione per eventuali altri con lo stesso problema.
1. Non serve installare libvirt e vagrant-libvirt (si possono rimuovere se installati)
2. Impostare come provider predefinito VirtualBox invece di libvirt con il comando:
`export VAGRANT_DEFAULT_PROVIDER=virtualbox`
3. proseguire con la guida (vagrant up).

Franco

**Comment by daserzw** [comment]
Grazie Franco, si in effetti questo Vagrantfile e' stato cucito addosso a Virtualbox, con KVM o altri hypervisor non puo' funzionare a meno di modifiche ala parte rete.
