### ISSUE TITLE
link di verifica errati

### ISSUE THREAD

**Issue by leliocampanile** [daserzw/IdP3-vagrant#2]
Gli ultimi 2 link per la verificano sembrano essere sbagliati:

LINK: https://idp.example.org CONTENUTO: una pagina di errore di Apache Tomcat con contenuto HTTP Status 404 - /idp
LINK: https://idp.example.org/idp CONTENUTO: una pagina dal titolo shibsp::ConfigurationException

Il primo è evidentemente sbagliato, metre il secondo non ritorna la ConfigurationException ma erroro 404 (probabilmente è il link che andava sopra?)

**Comment by daserzw** [comment]
Si, un refuso. Trovi i link corretti nel README.md aggiornato.
